apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coredns
  namespace: argocd
  labels:
    app.kubernetes.io/name: coredns
    app.kubernetes.io/group: infrastructure
    app.kubernetes.io/managed-by: applications
  finalizers:
    - resources-finalizer.argoproj.io
spec:
  project: default
  source:
    repoURL: https://coredns.github.io/helm
    chart: coredns
    targetRevision: '1.28.1'
    helm:
      releaseName: coredns
      values: |
        replicaCount: 0
        image:
          repository: coredns/coredns
          tag: "1.12.0"
          pullPolicy: IfNotPresent
        service:
          enabled: false
        deployment:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 5m
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/selector
        - /spec/template/metadata/labels
        - /spec/template/spec/containers/0/image
    - group: ""
      kind: Service
      jsonPointers:
        - /spec/clusterIP
        - /spec/clusterIPs
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
      name: coredns
      jqPathExpressions:
        - '.rules[] | select(.nonResourceURLs[]? | contains("/metrics"))'
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
      name: coredns
