apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coredns
  namespace: argocd
  labels:
    app.kubernetes.io/name: coredns
    app.kubernetes.io/group: infrastructure
    app.kubernetes.io/managed-by: applications
  finalizers:
    - resources-finalizer.argoproj.io
spec:
  project: default
  source:
    repoURL: https://coredns.github.io/helm
    chart: coredns
    targetRevision: '*'
    helm:
      releaseName: coredns
      values: |
        replicaCount: 2
        image:
          repository: coredns/coredns
          tag: "1.12.0"
          pullPolicy: IfNotPresent
        service:
          type: ClusterIP
          # Let the system assign the ClusterIP to avoid conflict with system CoreDNS
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 128Mi
        nodeSelector:
          kubernetes.io/os: linux
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                      - key: app.kubernetes.io/name
                        operator: In
                        values:
                          - coredns
                  topologyKey: kubernetes.io/hostname
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - SkipDryRunOnMissingResource=true
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 5m
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/selector
        - /spec/template/spec/containers/0/image
    - group: ""
      kind: Service
      jsonPointers:
        - /spec/clusterIPs
        - /spec/clusterIP
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/conversion
        - /status
        - /metadata/annotations
