apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vietcgi/kubernetes-platform-stack
    targetRevision: main
    path: helm/my-app
    helm:
      parameters:
      - name: image.repository
        value: "nginx"
      - name: image.pullPolicy
        value: "IfNotPresent"
      - name: image.tag
        value: "1.27-alpine"
      - name: istio.enabled
        value: "false"
      - name: prometheus.enabled
        value: "false"
  destination:
    server: https://kubernetes.default.svc
    namespace: app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
  revisionHistoryLimit: 10
  ignoreDifferences:
  - group: networking.istio.io
    kind: DestinationRule
    jsonPointers:
    - /spec
  - group: networking.istio.io
    kind: VirtualService
    jsonPointers:
    - /spec
  - group: security.istio.io
    kind: PeerAuthentication
    jsonPointers:
    - /spec
  - group: security.istio.io
    kind: AuthorizationPolicy
    jsonPointers:
    - /spec
