apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vietcgi/kubernetes-platform-stack
    targetRevision: main
    path: helm/my-app
    helm:
      parameters:
      - name: image.pullPolicy
        value: "IfNotPresent"
      - name: image.tag
        value: "latest"
      - name: istio.enabled
        value: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: app
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
  revisionHistoryLimit: 10
  ignoreDifferences:
  - group: networking.istio.io
    kind: DestinationRule
    jsonPointers:
    - /spec
  - group: networking.istio.io
    kind: VirtualService
    jsonPointers:
    - /spec
  - group: security.istio.io
    kind: PeerAuthentication
    jsonPointers:
    - /spec
  - group: security.istio.io
    kind: AuthorizationPolicy
    jsonPointers:
    - /spec
