# Enterprise ApplicationSet Template
# Generates all platform applications from a single source of truth
# Uses Helm repositories as the source for all applications
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform-applications
  namespace: argocd
  labels:
    app.kubernetes.io/name: platform-applicationset
    app.kubernetes.io/part-of: argocd
spec:
  goTemplate: true
  generators:
  # List-based generator using shared app configuration
  - list:
      elements:
      # Observability Stack
      - name: prometheus
        namespace: monitoring
        repoURL: https://prometheus-community.github.io/helm-charts
        chart: kube-prometheus-stack
        version: "*"
        syncPolicy: aggressive
        group: observability

      - name: loki
        namespace: monitoring
        repoURL: https://grafana.github.io/helm-charts
        chart: loki-stack
        version: "*"
        syncPolicy: aggressive
        group: observability

      - name: tempo
        namespace: monitoring
        repoURL: https://grafana.github.io/helm-charts
        chart: tempo
        version: "*"
        syncPolicy: aggressive
        group: observability

      # Service Mesh
      - name: istio
        namespace: istio-system
        repoURL: https://istio-release.storage.googleapis.com/charts
        chart: istiod
        version: "*"
        syncPolicy: conservative
        group: service_mesh

      # Security Layer
      - name: cert-manager
        namespace: cert-manager
        repoURL: https://charts.jetstack.io
        chart: cert-manager
        version: "*"
        syncPolicy: aggressive
        group: security

      - name: vault
        namespace: vault
        repoURL: https://helm.releases.hashicorp.com
        chart: vault
        version: "*"
        syncPolicy: aggressive
        group: security

      - name: falco
        namespace: falco
        repoURL: https://falcosecurity.github.io/charts
        chart: falco
        version: "*"
        syncPolicy: aggressive
        group: security

      - name: kyverno
        namespace: kyverno
        repoURL: https://kyverno.github.io/kyverno
        chart: kyverno
        version: "*"
        syncPolicy: aggressive
        group: security

      - name: sealed-secrets
        namespace: sealed-secrets
        repoURL: https://bitnami-labs.github.io/sealed-secrets
        chart: sealed-secrets
        version: "*"
        syncPolicy: aggressive
        group: security

      # Governance Layer
      - name: gatekeeper
        namespace: gatekeeper-system
        repoURL: https://open-policy-agent.github.io/gatekeeper/charts
        chart: gatekeeper
        version: "*"
        syncPolicy: aggressive
        group: governance

  template:
    metadata:
      name: '{{ .name }}'
      labels:
        app.kubernetes.io/name: '{{ .name }}'
        app.kubernetes.io/group: '{{ .group }}'
        app.kubernetes.io/managed-by: applicationset
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: '{{ .repoURL }}'
        chart: '{{ .chart }}'
        targetRevision: '{{ .version }}'
        helm:
          releaseName: '{{ .name }}'
          values: |
            {}
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ .namespace }}'
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - RespectIgnoreDifferences=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
      ignoreDifferences:
        - group: apiextensions.k8s.io
          kind: CustomResourceDefinition
          jsonPointers:
            - /spec/conversion
        - group: apiextensions.k8s.io
          kind: CustomResourceDefinition
          jsonPointers:
            - /status
  goTemplateOptions: ["missingkey=error"]
  templatePatch: |
    spec:
      syncPolicy:
        automated:
          prune: {{ if eq .syncPolicy "aggressive" }}true{{ else }}false{{ end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: applicationset-defaults
  namespace: argocd
  labels:
    app.kubernetes.io/name: applicationset-defaults
data:
  # Platform applications inventory
  platform-apps: |
    observability:
      - prometheus
      - loki
      - tempo
    service_mesh:
      - istio
    security:
      - cert-manager
      - vault
      - falco
      - kyverno
      - sealed-secrets
    governance:
      - gatekeeper
