# Enterprise ApplicationSet Template
# Generates all platform applications from a single source of truth
# Uses Helm repositories as the source for all applications
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform-applications
  namespace: argocd
  labels:
    app.kubernetes.io/name: platform-applicationset
    app.kubernetes.io/part-of: argocd
spec:
  goTemplate: true
  generators:
  # List-based generator using shared app configuration
  - list:
      elements:
      # Observability Stack
      - name: prometheus
        namespace: monitoring
        repoURL: https://prometheus-community.github.io/helm-charts
        chart: kube-prometheus-stack
        version: "*"
        syncPolicy: aggressive
        group: observability
        syncWave: 1

      - name: loki
        namespace: monitoring
        repoURL: https://grafana.github.io/helm-charts
        chart: loki-stack
        version: "*"
        syncPolicy: aggressive
        group: observability
        syncWave: 1

      - name: tempo
        namespace: monitoring
        repoURL: https://grafana.github.io/helm-charts
        chart: tempo
        version: "*"
        syncPolicy: aggressive
        group: observability
        syncWave: 1

      # Service Mesh
      - name: istio
        namespace: istio-system
        repoURL: https://istio-release.storage.googleapis.com/charts
        chart: istiod
        version: "*"
        syncPolicy: conservative
        group: service_mesh
        syncWave: 2

      # Security Layer
      - name: cert-manager
        namespace: cert-manager
        repoURL: https://charts.jetstack.io
        chart: cert-manager
        version: "*"
        syncPolicy: aggressive
        group: security
        syncWave: 0

      - name: vault
        namespace: vault
        repoURL: https://helm.releases.hashicorp.com
        chart: vault
        version: "*"
        syncPolicy: aggressive
        group: security
        syncWave: 3

      - name: falco
        namespace: falco
        repoURL: https://falcosecurity.github.io/charts
        chart: falco
        version: "*"
        syncPolicy: aggressive
        group: security
        syncWave: 3

      - name: kyverno
        namespace: kyverno
        repoURL: https://kyverno.github.io/kyverno
        chart: kyverno
        version: "*"
        syncPolicy: aggressive
        group: security
        syncWave: 3

      - name: sealed-secrets
        namespace: sealed-secrets
        repoURL: https://bitnami-labs.github.io/sealed-secrets
        chart: sealed-secrets
        version: "*"
        syncPolicy: aggressive
        group: security
        syncWave: 3

      # Governance Layer
      - name: gatekeeper
        namespace: gatekeeper-system
        repoURL: https://open-policy-agent.github.io/gatekeeper/charts
        chart: gatekeeper
        version: "*"
        syncPolicy: aggressive
        group: governance
        syncWave: 3

      # Enterprise Features - Ingress & API Management
      - name: external-dns
        namespace: external-dns
        repoURL: https://kubernetes-sigs.github.io/external-dns/
        chart: external-dns
        version: "*"
        syncPolicy: aggressive
        group: infrastructure
        syncWave: 0

      - name: kong
        namespace: api-gateway
        repoURL: https://charts.konghq.com
        chart: kong
        version: "*"
        syncPolicy: aggressive
        group: infrastructure
        syncWave: 2

      # Enterprise Features - Storage & Backup
      - name: longhorn
        namespace: longhorn-system
        repoURL: https://charts.longhorn.io
        chart: longhorn
        version: "*"
        syncPolicy: aggressive
        group: infrastructure
        syncWave: 4

      - name: velero
        namespace: velero
        repoURL: https://vmware-tanzu.github.io/helm-charts
        chart: velero
        version: "*"
        syncPolicy: aggressive
        group: infrastructure
        syncWave: 4

      # Enterprise Features - Advanced Observability
      - name: jaeger
        namespace: tracing
        repoURL: https://jaegertracing.github.io/helm-charts
        chart: jaeger
        version: "*"
        syncPolicy: aggressive
        group: observability
        syncWave: 2

      # Enterprise Features - Container Registry
      - name: harbor
        namespace: harbor
        repoURL: https://helm.goharbor.io
        chart: harbor
        version: "*"
        syncPolicy: aggressive
        group: infrastructure
        syncWave: 4

  template:
    metadata:
      name: '{{ .name }}'
      labels:
        app.kubernetes.io/name: '{{ .name }}'
        app.kubernetes.io/group: '{{ .group }}'
        app.kubernetes.io/managed-by: applicationset
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: '{{ .repoURL }}'
        chart: '{{ .chart }}'
        targetRevision: '{{ .version }}'
        helm:
          releaseName: '{{ .name }}'
          values: |
            {{ if eq .name "cert-manager" }}
            # Enable CRD installation for cert-manager
            crds:
              enabled: true
            {{ else if eq .name "prometheus" }}
            # Kube-prometheus-stack needs extra settings for KIND
            prometheus:
              prometheusSpec:
                podMonitorNamespaceSelector: {}
            {{ else if eq .name "external-dns" }}
            # External DNS for automatic DNS record management
            policy: sync
            registry: txt
            txtOwnerId: external-dns
            {{ else if eq .name "longhorn" }}
            # Longhorn persistent storage
            persistence:
              defaultClassReplicaCount: 3
            defaultSettings:
              backupTarget: ""
              backupTargetCredentialSecret: ""
            {{ else if eq .name "velero" }}
            # Velero backup and disaster recovery
            configuration:
              backupStorageLocation:
                name: default
                provider: aws
                bucket: velero-backups
              schedules:
                daily:
                  schedule: "0 2 * * *"
                  template:
                    ttl: "720h"
            {{ else if eq .name "jaeger" }}
            # Jaeger distributed tracing with in-memory storage (suitable for KIND)
            provisionDataStore:
              cassandra: false
              elasticsearch: false
            storage:
              type: memory
            collector:
              service:
                type: LoadBalancer
            query:
              service:
                type: LoadBalancer
            {{ else if eq .name "kong" }}
            # Kong API Gateway with LoadBalancer and hostNetwork for KIND port access
            admin:
              enabled: true
              service:
                type: ClusterIP
            proxy:
              service:
                type: LoadBalancer
              containerPort: 8000
            # Use hostNetwork to make Kong accessible on host ports (80/443)
            podSecurityPolicy:
              enabled: false
            deployment:
              hostNetwork: true
            # Enable Kong Ingress Controller for ingress routing
            ingressController:
              enabled: true
              installCRDs: true
            {{ else if eq .name "harbor" }}
            # Harbor container registry
            persistence:
              enabled: true
              persistentVolumeClaim:
                registry:
                  size: 5Gi
            {{ else }}
            {}
            {{ end }}
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ .namespace }}'
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - RespectIgnoreDifferences=true
          - ServerSideApply=true
          - SkipDryRunOnMissingResource=true
        retry:
          limit: 10
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 5m
      ignoreDifferences:
        - group: apiextensions.k8s.io
          kind: CustomResourceDefinition
          jsonPointers:
            - /spec/conversion
            - /status
            - /metadata/annotations
  goTemplateOptions: ["missingkey=error"]
  templatePatch: |
    metadata:
      annotations:
        {{- if .syncWave }}
        argocd.argoproj.io/sync-wave: "{{ .syncWave }}"
        {{- end }}
    spec:
      syncPolicy:
        automated:
          prune: {{ if eq .syncPolicy "aggressive" }}true{{ else }}false{{ end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: applicationset-defaults
  namespace: argocd
  labels:
    app.kubernetes.io/name: applicationset-defaults
data:
  # Platform applications inventory
  platform-apps: |
    infrastructure:
      - external-dns
      - kong
      - longhorn
      - velero
      - harbor
    observability:
      - prometheus
      - loki
      - tempo
      - jaeger
    service_mesh:
      - istio
    security:
      - cert-manager
      - vault
      - falco
      - kyverno
      - sealed-secrets
    governance:
      - gatekeeper
